### ISSUE TITLE
More issues with pad_start

### ISSUE THREAD

**Issue by qwertymodo** [qwertymodo/msupcmplusplus#6]
pad_start applied to a top-level track seems to cause a song to start before the specified trim_start point instead of padding with silence.  Also, when applied to the parent of a sub_track, it seems to just result in a silent track, the length of the pad, e.g.

```
    {
      "track_number": 60,
      "title": "Light World 2",
      "sub_tracks": [
        {
          "file": "Disc 3\\08. Song of the Ancients - Fate.mp3",
          "loop": 1012136,
          "trim_start": 1340951,
          "trim_end": 10944724,
          "fade_in": 5000
        }
      ],
      "pad_start": 20000
    },
```

**Comment by qwertymodo** [comment]
Hmm... actually that second one seems to be a bug with the sub_track, pad_start is working correctly, but if you remove it, the sub_track generates nothing.

**Comment by qwertymodo** [comment]
I think this might be fixed in 89368c4cb98a1b8d249ace0096ec8f6fd24cd45e but I need to confirm.

**Comment by qwertymodo** [comment]
Another issue was just reported on Discord tonight.  Using pad_start with a loop value of 0 seems to trigger the loop-before-start  mode, except it uses garbage values and causes trims to fail with out of range errors.  This is new in RC2, and the same JSON file worked successfully in RC1.

**Comment by floresmatthew** [comment]
That was me.  Here are two snippets of JSON.  The first one does not work in RC2.  The second one does work as a workaround.  Both work in RC1.

Doesn't work

```
 {
        "track_number": 1,
        "title": "Opening Theme (HM64 - Ceremony of Passing)",
        "file": "tracks\\Harvest Moon 64\\Harvest Moon 64 Complete OST.wav",
        "trim_start": 9758450,
        "trim_end": 10421900,
        "fade_out": 44100,
        "pad_start": 75900,
        "normalization": -22
      },
```

Works
```
    {
        "track_number": 1,
        "title": "Opening Theme (HM64 - Ceremony of Passing)",
        "file": "tracks\\Harvest Moon 64\\Harvest Moon 64 Complete OST.wav",
        "trim_start": 9758450,
        "trim_end": 10421900,
        "fade_out": 44100,
        "pad_start": 75900,
        "normalization": -22,
        "loop": 9758450
      },
```

It seems adding a loop with the same value of trim_start will work for this.

**Comment by qwertymodo** [comment]
Should be fixed in https://github.com/qwertymodo/msupcmplusplus/commit/0336543698f04def14a10ac490f40d71422ee3b2 (i.e. RC3)
