### ISSUE TITLE
No Linux build instructions and project in its current state won't build on Linux

### ISSUE THREAD

**Issue by bitrot-alpha** [qwertymodo/msupcmplusplus#7]
It should be made clear that [qwertymodo/sox](https://github.com/qwertymodo/sox) needs to be downloaded to the /3rdparty/sox directory in order to build the project. Maybe revise README.md with this info?

Also, building on my machine (Fedora Linux 36) doesn't work because of this:
```
make -C 3rdparty/sox -s
Making all in lpc10
Making all in libgsm
Making all in src
make -C msupcm++ -s
In file included from sox_main.h:8,
                 from SoxWrapper.h:2,
                 from AudioBase.cpp:3:
/usr/include/c++/12/codecvt: In constructor ‘std::codecvt_utf8<char16_t, _Maxcode, _Mode>::codecvt_utf8(std::size_t)’:
../3rdparty/sox/src/util.h:196:19: error: expected unqualified-id before ‘(’ token
  196 | #define min(a, b) ((a) <= (b) ? (a) : (b))
      |                   ^
[And more of this]
```
Obviously, it doesn't make sense that a macro is messing up constructors or templates or any of the stuff included from the STL/etc, so there must be an error further up in the header or in one of the other listed files that the compiler didn't like. I looked in the file and changed a few things in an attempt to get it to compile, but no dice after 2 hours of research..

**Comment by qwertymodo** [comment]
The linux build has been broken since I added the command-line interface.  I'm not sure I'll be able to fix it, because it requires getting unicode handling to work in a cross-platform way, which is made complicated by Microsoft choosing to do everything differently than everyone else.  From the log, it looks like v0.6 is the last one that worked on Linux.

**Comment by qwertymodo** [comment]
Ok, I think the linux build might be working again.  As for downloading the 3rdparty/ dependencies, that should NOT be done manually, instead that is handled by running 

`git submodule update --init --recursive`

before running make.
